version: 2
updates:
  - package-ecosystem: gradle
    directory: /sleep-analysis-dreamapp-api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: /WereableApp
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /sleep-functions/functions
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

