import { z } from "zod";

/**
 * Weekly Sleep Statistics Schema
 * 
 * Schema for storing aggregated weekly sleep statistics for a user.
 * This document is generated by processing the last 7 sleep records
 * and provides insights into sleep patterns and trends.
 */
export const weeklySleepStatsSchema = z.object({
  // Identification
  uidUser: z.string().min(1),
  
  // Time period
  weekStartDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, {
    message: "weekStartDate must be in YYYY-MM-DD format"
  }),
  weekEndDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, {
    message: "weekEndDate must be in YYYY-MM-DD format"
  }),
  
  // Data quality
  totalNights: z.number().min(1).max(7),
  dataQualityScore: z.number().min(0).max(100),
  
  // Sleep duration statistics (in minutes)
  avgSleepDuration: z.number().min(0),
  minSleepDuration: z.number().min(0),
  maxSleepDuration: z.number().min(0),
  totalSleepTime: z.number().min(0),
  
  // Sleep efficiency
  avgSleepEfficiency: z.number().min(0).max(100),
  consistencyScore: z.number().min(0).max(100), // How consistent are the sleep times
  
  // Sleep phases distribution (percentages)
  avgLightSleepPercentage: z.number().min(0).max(100),
  avgDeepSleepPercentage: z.number().min(0).max(100),
  avgRemSleepPercentage: z.number().min(0).max(100),
  
  // Sleep phases duration (in minutes)
  avgLightSleepMinutes: z.number().min(0),
  avgDeepSleepMinutes: z.number().min(0),
  avgRemSleepMinutes: z.number().min(0),
  avgAwakeDuration: z.number().min(0),
  
  // Sleep quality distribution
  qualityDistribution: z.object({
    excellent: z.number().min(0).max(7),
    good: z.number().min(0).max(7),
    fair: z.number().min(0).max(7),
    poor: z.number().min(0).max(7)
  }),
  dominantQuality: z.enum(['POOR', 'FAIR', 'GOOD', 'EXCELLENT']),
  
  // Heart rate statistics
  avgHeartRate: z.number().min(30).max(200),
  minHeartRate: z.number().min(30).max(200),
  maxHeartRate: z.number().min(30).max(200),
  heartRateVariability: z.number().min(0), // Standard deviation of avg heart rates
  
  // HRV statistics
  avgRmssd: z.number().min(0).max(200),
  avgSdnn: z.number().min(0).max(200),
  hrvTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  
  // Sleep disruption
  avgAwakeningsCount: z.number().min(0),
  avgMovement: z.number().min(0).max(100),
  
  // Sleep timing patterns
  avgBedtime: z.string(), // Average bedtime in HH:MM format
  avgWakeTime: z.string(), // Average wake time in HH:MM format
  bedtimeConsistency: z.number().min(0).max(100), // How consistent are bedtimes
  
  // Trends compared to previous week
  sleepDurationTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  sleepQualityTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  
  // Metadata
  createdAt: z.number().positive(),
  updatedAt: z.number().positive(),
  dataVersion: z.string().default('1.0'),
  
  // Source data info
  sourceNights: z.array(z.string()),
});

export type WeeklySleepStats = z.infer<typeof weeklySleepStatsSchema>;
