import { z } from "zod";

/**
 * Monthly Sleep Statistics Schema
 * 
 * Schema for storing aggregated monthly sleep statistics for a user.
 * This document is generated by processing all sleep records in a month
 * and provides comprehensive insights into sleep patterns and trends.
 */
export const monthlySleepStatsSchema = z.object({
  // Identification
  uidUser: z.string().min(1),
  
  // Time period
  year: z.number().int().min(2020).max(2100),
  month: z.number().int().min(1).max(12),
  monthStartDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, {
    message: "monthStartDate must be in YYYY-MM-DD format"
  }),
  monthEndDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, {
    message: "monthEndDate must be in YYYY-MM-DD format"
  }),
  
  // Data coverage
  totalNights: z.number().min(1).max(31), // Number of nights with data in this month
  totalDaysInMonth: z.number().min(28).max(31), // Total days in the month
  dataCompleteness: z.number().min(0).max(100), // Percentage of days with data
  dataQualityScore: z.number().min(0).max(100), // Average data quality
  
  // Sleep duration statistics (in minutes)
  avgSleepDuration: z.number().min(0),
  minSleepDuration: z.number().min(0),
  maxSleepDuration: z.number().min(0),
  totalSleepTime: z.number().min(0),
  sleepDurationStdDev: z.number().min(0), // Standard deviation of sleep duration
  
  // Sleep efficiency
  avgSleepEfficiency: z.number().min(0).max(100),
  minSleepEfficiency: z.number().min(0).max(100),
  maxSleepEfficiency: z.number().min(0).max(100),
  sleepEfficiencyStdDev: z.number().min(0),
  
  // Sleep phases distribution (averages and totals)
  avgLightSleepMinutes: z.number().min(0),
  avgDeepSleepMinutes: z.number().min(0),
  avgRemSleepMinutes: z.number().min(0),
  avgAwakeDuration: z.number().min(0),
  
  // Sleep phases as percentages
  avgLightSleepPercentage: z.number().min(0).max(100),
  avgDeepSleepPercentage: z.number().min(0).max(100),
  avgRemSleepPercentage: z.number().min(0).max(100),
  
  // Monthly totals (in hours)
  totalLightSleepHours: z.number().min(0),
  totalDeepSleepHours: z.number().min(0),
  totalRemSleepHours: z.number().min(0),
  totalAwakeHours: z.number().min(0),
  
  // Sleep quality distribution and trends
  qualityDistribution: z.object({
    excellent: z.number().min(0).max(31),
    good: z.number().min(0).max(31),
    fair: z.number().min(0).max(31),
    poor: z.number().min(0).max(31)
  }),
  dominantQuality: z.enum(['POOR', 'FAIR', 'GOOD', 'EXCELLENT']),
  qualityTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  
  // Heart rate statistics
  avgHeartRate: z.number().min(30).max(200),
  minHeartRate: z.number().min(30).max(200),
  maxHeartRate: z.number().min(30).max(200),
  heartRateStdDev: z.number().min(0),
  
  // HRV statistics
  avgRmssd: z.number().min(0).max(200),
  avgSdnn: z.number().min(0).max(200),
  rmssdStdDev: z.number().min(0),
  sdnnStdDev: z.number().min(0),
  hrvTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  
  // Sleep disruption patterns
  avgAwakeningsCount: z.number().min(0),
  totalAwakenings: z.number().min(0),
  avgMovement: z.number().min(0).max(100),
  
  // Sleep timing consistency
  avgBedtime: z.string(), // Average bedtime in HH:MM format
  avgWakeTime: z.string(), // Average wake time in HH:MM format
  bedtimeStdDev: z.number().min(0), // Bedtime consistency (minutes)
  wakeTimeStdDev: z.number().min(0), // Wake time consistency (minutes)
  scheduleConsistency: z.number().min(0).max(100), // Overall schedule consistency score
  
  // Weekly patterns analysis
  bestDayOfWeek: z.enum(['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']),
  worstDayOfWeek: z.enum(['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']),
  weekdayVsWeekendDifference: z.number(), // Minutes difference in average sleep duration
  
  // Monthly trends and comparisons
  sleepDurationTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  sleepQualityTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  consistencyTrend: z.enum(['IMPROVING', 'STABLE', 'DECLINING']),
  
  // Goal achievement (assuming 7-9 hours target)
  optimalSleepNights: z.number().min(0).max(31), // Nights with 7-9 hours sleep
  optimalSleepPercentage: z.number().min(0).max(100),
  
  // Sleep debt analysis
  recommendedSleepMinutes: z.number().default(480), // 8 hours recommended
  avgSleepDebt: z.number(), // Average daily sleep debt (can be negative for surplus)
  totalSleepDebt: z.number(), // Total monthly sleep debt
  
  // Recovery metrics
  recoveryDays: z.number().min(0).max(31), // Days with above-average recovery
  stressIndicatorDays: z.number().min(0).max(31), // Days showing potential stress indicators
  
  // Comparison with previous month (if available)
  previousMonthComparison: z.object({
    sleepDurationChange: z.number(),
    sleepQualityChange: z.number(),
    consistencyChange: z.number(),
    hasData: z.boolean()
  }).optional(),
  
  // Weekly breakdown summary
  weeklyBreakdown: z.array(z.object({
    weekNumber: z.number().min(1).max(5), // Week of month
    avgSleepDuration: z.number().min(0),
    avgSleepEfficiency: z.number().min(0).max(100),
    dominantQuality: z.enum(['POOR', 'FAIR', 'GOOD', 'EXCELLENT']),
    nightsWithData: z.number().min(0).max(7)
  })),
  
  // Metadata
  createdAt: z.number().positive(),
  updatedAt: z.number().positive(),
  dataVersion: z.string().default('1.0'),
  
  // Source data info
  sourceNights: z.array(z.string()), // Array of document IDs that were used
  sourceWeeks: z.array(z.string()).optional(), // Array of weekly stats document IDs if available
});

export type MonthlySleepStats = z.infer<typeof monthlySleepStatsSchema>;
